// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

fn main() -> std::io::Result<()> {
    #[cfg(feature = "regenerate-proto")]
    {
        use std::path::PathBuf;

        let manifest_dir =
            PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
        let out_path = manifest_dir.join("src").join("gen_webui.rs");

        let mut config = prost_build::Config::new();
        config.type_attribute(".", "#[derive(serde::Serialize, serde::Deserialize)]");

        // Build into OUT_DIR first (prost-build requirement), then copy to src/.
        config.compile_protos(&["proto/webui.proto"], &["proto/"])?;

        // Find the generated file in OUT_DIR and copy to src/gen_webui.rs.
        let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
        let generated = out_dir.join("webui.rs");

        let header = "// Copyright (c) Microsoft Corporation.\n\
                      // Licensed under the MIT license.\n\
                      \n\
                      // This file is @generated by prost-build from proto/webui.proto.\n\
                      // Do not edit manually. Regenerate with: cargo xtask proto\n";

        let content = std::fs::read_to_string(&generated)?;
        std::fs::write(&out_path, format!("{header}{content}"))?;
    }

    Ok(())
}
