[advisories]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "MPL-2.0",
    "Unicode-3.0",
    "BSD-3-Clause",
    "Zlib",
]
confidence-threshold = 0.8

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
skip = [
    { name = "convert_case" },
    { name = "getrandom" },
    { name = "hashbrown" },
    { name = "r-efi" },
    { name = "socket2" },
    { name = "windows-sys" },
]
