[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[features]
windows-app-sdk-tools = ["dep:windows-bindgen"]

[dependencies]
console = { workspace = true }
ctrlc = { workspace = true }
serde_json = { workspace = true }
windows-bindgen = { workspace = true, optional = true }
sha2 = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
which = { workspace = true }

[lints]
workspace = true
