// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';
import { test } from 'node:test';

const packageRoot = process.cwd();
const repoRoot = resolve(packageRoot, '../..');

test('Linux local IPC entries and real browser fixture match generated bytes', () => {
  execFileSync(process.execPath, [resolve(packageRoot, 'scripts/linux-assets.mjs'), '--check'], {
    cwd: repoRoot, stdio: 'pipe',
  });
  execFileSync(process.execPath, [
    resolve(repoRoot, 'crates/webui-desktop/tests/fixtures/build-linux-local.mjs'), '--check',
  ], { cwd: repoRoot, stdio: 'pipe' });
});
