// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use std::collections::HashMap;

use prost::Message;

use crate::error::{DesktopError, Result};

/// Current desktop IPC envelope version.
pub const IPC_VERSION: u32 = 1;

/// Default maximum IPC frame size.
pub const DEFAULT_MAX_IPC_PAYLOAD_BYTES: usize = 1024 * 1024;

/// Protobuf request frame for desktop IPC.
#[derive(Clone, PartialEq, Message)]
pub struct DesktopIpcRequest {
    /// Envelope version.
    #[prost(uint32, tag = "1")]
    pub version: u32,
    /// Client-generated request identifier.
    #[prost(uint64, tag = "2")]
    pub request_id: u64,
    /// Allowlisted method identifier.
    #[prost(string, tag = "3")]
    pub method: String,
    /// App-specific protobuf payload.
    #[prost(bytes = "vec", tag = "4")]
    pub payload: Vec<u8>,
}

/// Protobuf response frame for desktop IPC.
#[derive(Clone, PartialEq, Message)]
pub struct DesktopIpcResponse {
    /// Envelope version.
    #[prost(uint32, tag = "1")]
    pub version: u32,
    /// Request identifier copied from the request when available.
    #[prost(uint64, tag = "2")]
    pub request_id: u64,
    /// Payload or structured error result.
    #[prost(oneof = "desktop_ipc_response::Result", tags = "3, 4")]
    pub result: Option<desktop_ipc_response::Result>,
}

/// Oneof module generated manually for [`DesktopIpcResponse`].
pub mod desktop_ipc_response {
    /// Payload or structured error result.
    #[derive(Clone, PartialEq, prost::Oneof)]
    pub enum Result {
        /// App-specific protobuf response payload.
        #[prost(bytes, tag = "3")]
        Payload(Vec<u8>),
        /// Structured desktop IPC error.
        #[prost(message, tag = "4")]
        Error(super::DesktopIpcError),
    }
}

/// Structured error returned over desktop IPC.
#[derive(Clone, PartialEq, Message)]
pub struct DesktopIpcError {
    /// Stable machine-readable error code.
    #[prost(string, tag = "1")]
    pub code: String,
    /// Plain, human-readable message.
    #[prost(string, tag = "2")]
    pub message: String,
    /// Actionable help text.
    #[prost(string, tag = "3")]
    pub help: String,
}

/// Error returned by an application IPC handler.
#[derive(Clone, Debug)]
pub struct IpcHandlerError {
    code: String,
    message: String,
    help: String,
}

impl IpcHandlerError {
    /// Create a structured IPC handler error.
    #[must_use]
    pub fn new(
        code: impl Into<String>,
        message: impl Into<String>,
        help: impl Into<String>,
    ) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
            help: help.into(),
        }
    }

    fn into_frame(self) -> DesktopIpcError {
        DesktopIpcError {
            code: self.code,
            message: self.message,
            help: self.help,
        }
    }
}

type IpcHandler = dyn Fn(&[u8]) -> std::result::Result<Vec<u8>, IpcHandlerError> + Send + Sync;

/// Allowlisted protobuf IPC method registry.
#[derive(Default)]
pub struct IpcRegistry {
    handlers: HashMap<String, Box<IpcHandler>>,
    max_payload_bytes: usize,
}

impl IpcRegistry {
    /// Create an empty IPC registry.
    #[must_use]
    pub fn new() -> Self {
        Self {
            handlers: HashMap::new(),
            max_payload_bytes: DEFAULT_MAX_IPC_PAYLOAD_BYTES,
        }
    }

    /// Set the maximum accepted IPC frame size.
    #[must_use]
    pub fn with_max_payload_bytes(mut self, max_payload_bytes: usize) -> Self {
        self.max_payload_bytes = max_payload_bytes;
        self
    }

    /// Register an allowlisted IPC method.
    pub fn register<F>(&mut self, method: impl Into<String>, handler: F)
    where
        F: Fn(&[u8]) -> std::result::Result<Vec<u8>, IpcHandlerError> + Send + Sync + 'static,
    {
        self.handlers.insert(method.into(), Box::new(handler));
    }

    /// Register a typed protobuf IPC method.
    ///
    /// # Type parameters
    ///
    /// `Req` and `Resp` are application protobuf message types generated by
    /// `prost`.
    pub fn register_protobuf<Req, Resp, F>(&mut self, method: impl Into<String>, handler: F)
    where
        Req: Message + Default,
        Resp: Message,
        F: Fn(Req) -> std::result::Result<Resp, IpcHandlerError> + Send + Sync + 'static,
    {
        self.register(method, move |payload| {
            let request = Req::decode(payload).map_err(|err| {
                IpcHandlerError::new(
                    "invalid-payload",
                    format!("failed to decode protobuf IPC payload: {err}"),
                    "send the protobuf message type registered for this desktop command",
                )
            })?;
            let response = handler(request)?;
            let mut out = Vec::with_capacity(response.encoded_len());
            response.encode(&mut out).map_err(|err| {
                IpcHandlerError::new(
                    "encode-failed",
                    format!("failed to encode protobuf IPC response: {err}"),
                    "check the desktop command response type",
                )
            })?;
            Ok(out)
        });
    }

    /// Dispatch one encoded IPC frame and return an encoded response frame.
    ///
    /// Decode failures are returned as structured IPC frames with request id 0
    /// when possible so browser callers receive one consistent binary shape.
    pub fn dispatch_frame(&self, frame: &[u8]) -> Result<Vec<u8>> {
        if frame.len() > self.max_payload_bytes {
            return self.encode_error(
                0,
                "payload-too-large",
                "desktop IPC frame exceeds the configured size limit",
                "send a smaller protobuf message or raise the trusted app IPC limit",
            );
        }

        let request = match DesktopIpcRequest::decode(frame) {
            Ok(request) => request,
            Err(err) => {
                return self.encode_error(
                    0,
                    "invalid-ipc-frame",
                    format!("failed to decode desktop IPC request: {err}"),
                    "send a DesktopIpcRequest protobuf frame",
                );
            }
        };

        if request.version != IPC_VERSION {
            return self.encode_error(
                request.request_id,
                "unsupported-ipc-version",
                format!("unsupported desktop IPC version {}", request.version),
                "regenerate the desktop IPC client for this WebUI version",
            );
        }

        if request.payload.len() > self.max_payload_bytes {
            return Err(DesktopError::IpcPayloadTooLarge {
                size: request.payload.len(),
                max_bytes: self.max_payload_bytes,
            });
        }

        let Some(handler) = self.handlers.get(&request.method) else {
            return self.encode_error(
                request.request_id,
                "unknown-method",
                format!("unknown desktop IPC method '{}'", request.method),
                "register the method in the Rust desktop IPC registry",
            );
        };

        match handler(&request.payload) {
            Ok(payload) => self.encode_response(DesktopIpcResponse {
                version: IPC_VERSION,
                request_id: request.request_id,
                result: Some(desktop_ipc_response::Result::Payload(payload)),
            }),
            Err(err) => self.encode_response(DesktopIpcResponse {
                version: IPC_VERSION,
                request_id: request.request_id,
                result: Some(desktop_ipc_response::Result::Error(err.into_frame())),
            }),
        }
    }

    fn encode_error(
        &self,
        request_id: u64,
        code: impl Into<String>,
        message: impl Into<String>,
        help: impl Into<String>,
    ) -> Result<Vec<u8>> {
        self.encode_response(DesktopIpcResponse {
            version: IPC_VERSION,
            request_id,
            result: Some(desktop_ipc_response::Result::Error(DesktopIpcError {
                code: code.into(),
                message: message.into(),
                help: help.into(),
            })),
        })
    }

    fn encode_response(&self, response: DesktopIpcResponse) -> Result<Vec<u8>> {
        let mut out = Vec::with_capacity(response.encoded_len());
        response.encode(&mut out)?;
        Ok(out)
    }
}

#[cfg(test)]
#[allow(clippy::disallowed_methods)]
mod tests {
    use super::*;

    fn encode_request(method: &str, payload: &[u8]) -> Vec<u8> {
        let request = DesktopIpcRequest {
            version: IPC_VERSION,
            request_id: 42,
            method: method.to_string(),
            payload: payload.to_vec(),
        };
        let mut bytes = Vec::new();
        request.encode(&mut bytes).unwrap();
        bytes
    }

    #[test]
    fn dispatches_registered_method() {
        let mut registry = IpcRegistry::new();
        registry.register("echo", |payload| Ok(payload.to_vec()));

        let response = registry
            .dispatch_frame(&encode_request("echo", b"hello"))
            .unwrap();
        let decoded = DesktopIpcResponse::decode(response.as_slice()).unwrap();

        assert_eq!(decoded.request_id, 42);
        match decoded.result.unwrap() {
            desktop_ipc_response::Result::Payload(payload) => assert_eq!(payload, b"hello"),
            desktop_ipc_response::Result::Error(err) => panic!("unexpected error: {}", err.code),
        }
    }

    #[test]
    fn unknown_method_returns_structured_error() {
        let registry = IpcRegistry::new();
        let response = registry
            .dispatch_frame(&encode_request("missing", b"hello"))
            .unwrap();
        let decoded = DesktopIpcResponse::decode(response.as_slice()).unwrap();

        match decoded.result.unwrap() {
            desktop_ipc_response::Result::Error(err) => {
                assert_eq!(err.code, "unknown-method");
                assert!(!err.help.is_empty());
            }
            desktop_ipc_response::Result::Payload(_) => panic!("expected error"),
        }
    }

    #[test]
    fn invalid_frame_returns_structured_error() {
        let registry = IpcRegistry::new();
        let response = registry.dispatch_frame(b"not protobuf").unwrap();
        let decoded = DesktopIpcResponse::decode(response.as_slice()).unwrap();

        assert_eq!(decoded.request_id, 0);
        match decoded.result.unwrap() {
            desktop_ipc_response::Result::Error(err) => assert_eq!(err.code, "invalid-ipc-frame"),
            desktop_ipc_response::Result::Payload(_) => panic!("expected error"),
        }
    }

    #[derive(Clone, PartialEq, Message)]
    struct EchoRequest {
        #[prost(string, tag = "1")]
        value: String,
    }

    #[derive(Clone, PartialEq, Message)]
    struct EchoResponse {
        #[prost(string, tag = "1")]
        value: String,
    }

    #[test]
    fn dispatches_typed_protobuf_method() {
        let mut registry = IpcRegistry::new();
        registry.register_protobuf("echo.typed", |request: EchoRequest| {
            Ok(EchoResponse {
                value: request.value,
            })
        });

        let mut payload = Vec::new();
        EchoRequest {
            value: "typed".to_string(),
        }
        .encode(&mut payload)
        .unwrap();

        let response = registry
            .dispatch_frame(&encode_request("echo.typed", &payload))
            .unwrap();
        let decoded = DesktopIpcResponse::decode(response.as_slice()).unwrap();
        let desktop_ipc_response::Result::Payload(payload) = decoded.result.unwrap() else {
            panic!("expected payload");
        };
        let typed = EchoResponse::decode(payload.as_slice()).unwrap();
        assert_eq!(typed.value, "typed");
    }
}
