// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

//! Parser plugin trait and built-in plugin implementations.
//!
//! The plugin system is framework-aware but phase-local — parser plugins
//! classify framework-owned attributes, capture plugin-facing component templates,
//! and emit per-element hydration metadata for the handler.

pub mod fast;
pub mod fast_v2;
pub mod fast_v3;
pub mod webui;

use crate::component_registry::Component;
use crate::{ParserOptions, Result};

/// Parser-owned decision about how an attribute should be handled.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttributeAction {
    /// Let the parser process the attribute normally.
    Keep,
    /// Skip the attribute without incrementing the element binding count.
    Skip,
    /// Skip the attribute and count it as a dynamic binding.
    SkipAndCountBinding,
}

/// Build artifacts extracted from a parser plugin after parsing completes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParserPluginArtifacts {
    /// The plugin did not produce any post-parse artifacts.
    None,
    /// Client component templates keyed by tag name.
    ComponentTemplates(Vec<ComponentTemplateArtifact>),
}

/// Client template payload generated by a parser plugin for one component.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComponentTemplateArtifact {
    /// Component custom-element tag name.
    pub tag_name: String,
    /// Non-WebUI plugin template payload, such as FAST `<f-template>` HTML.
    pub template: String,
    /// WebUI JSON-safe template metadata.
    pub template_json: String,
    /// WebUI component-local JavaScript condition closure array.
    pub template_functions: String,
    /// Sorted, deduplicated hydration key surface this plugin derives for the
    /// component — the fields the client restores from the bootstrap state. Each
    /// plugin owns how it computes them: the WebUI plugin unions the template's
    /// reactive roots with the `@observable`/`@attr` names it scans from
    /// `Component::script_source`, while other plugins may use a different
    /// strategy or leave it empty. The build aggregates these across components
    /// into the protocol-level projection allowlist.
    pub hydration_keys: Vec<String>,
}

impl ComponentTemplateArtifact {
    /// Create a non-WebUI template payload.
    #[must_use]
    pub fn template(tag_name: String, template: String) -> Self {
        Self {
            tag_name,
            template,
            template_json: String::new(),
            template_functions: String::new(),
            hydration_keys: Vec::new(),
        }
    }

    /// Create a WebUI split metadata/function payload.
    ///
    /// The hydration surface starts empty; the producing plugin attaches it with
    /// [`Self::with_hydration_keys`] once it has derived the keys.
    #[must_use]
    pub fn webui(tag_name: String, template_json: String, template_functions: String) -> Self {
        Self {
            tag_name,
            template: String::new(),
            template_json,
            template_functions,
            hydration_keys: Vec::new(),
        }
    }

    /// Attach the hydration key surface this plugin derived for the component.
    ///
    /// This is the plugin-agnostic hook for the hydration surface: any plugin —
    /// the WebUI plugin, a FAST plugin, or a third-party one — computes its own
    /// keys (the fields the client restores from bootstrap state) and attaches
    /// them here in a single born-complete expression. The build aggregates
    /// these across components into the protocol-level projection allowlist.
    /// Keys must be sorted and deduplicated.
    #[must_use]
    pub fn with_hydration_keys(mut self, hydration_keys: Vec<String>) -> Self {
        self.hydration_keys = hydration_keys;
        self
    }
}

/// A parser plugin that can customize template parsing behavior.
///
/// Plugins receive callbacks at key points during HTML parsing:
/// - **Fragment lifecycle**: `start_fragment` before a fragment parse begins
/// - **Component registration**: `register_component_template` when a plugin-facing component template is finalized
/// - **Attribute classification**: `classify_attribute` for framework-specific attrs
/// - **Element completion**: `finish_element` after attributes are processed
///
/// WebUI calls these hooks during parsing; plugins decide what (if anything) to do.
pub trait ParserPlugin {
    /// Called before parsing begins for a fragment.
    ///
    /// Plugins can use this to reset fragment-local counters while preserving
    /// global build-level state such as tracked component templates.
    fn start_fragment(&mut self, _fragment_id: &str) {}

    /// Called when parser output options change.
    fn configure(&mut self, _options: &ParserOptions) {}

    /// Called with the plugin-facing component template for the active CSS/DOM
    /// strategies. Authored root `<template>` attributes are preserved here;
    /// the SSR/internal parse view may strip runtime-only attributes.
    ///
    /// `component` carries the build-time metadata a plugin needs to author its
    /// own hydration strategy — notably [`Component::script_source`], the raw
    /// authored client module. The registry never interprets that source, so a
    /// plugin is free to scan it (as the WebUI plugin does for `@observable`/`@attr`),
    /// parse it differently, or ignore it, and populate
    /// [`ComponentTemplateArtifact::hydration_keys`] accordingly.
    fn register_component_template(
        &mut self,
        tag_name: &str,
        component: &Component,
        processed_template: &str,
    ) -> Result<()>;

    /// Decide how a framework-owned attribute should be handled.
    fn classify_attribute(&mut self, attr_name: &str) -> AttributeAction;

    /// Called after all attributes on an element have been processed.
    /// `binding_attribute_count` is the number of dynamic attribute bindings found.
    /// Returns optional opaque bytes to emit as a `Plugin` protocol fragment.
    fn finish_element(&mut self, binding_attribute_count: u32) -> Option<Vec<u8>>;

    /// Consume the plugin and return any build artifacts it captured.
    ///
    /// # Errors
    ///
    /// Returns an error if the plugin encountered an invalid template construct
    /// while producing its artifacts (e.g. an invalid `@event` handler).
    fn into_artifacts(self: Box<Self>) -> Result<ParserPluginArtifacts> {
        Ok(ParserPluginArtifacts::None)
    }
}

#[cfg(test)]
mod artifact_tests {
    use super::ComponentTemplateArtifact;

    #[test]
    fn template_constructor_starts_with_no_hydration_surface() {
        let artifact = ComponentTemplateArtifact::template("x-a".into(), "<p></p>".into());
        assert_eq!(artifact.tag_name, "x-a");
        assert_eq!(artifact.template, "<p></p>");
        assert!(artifact.template_json.is_empty());
        assert!(artifact.template_functions.is_empty());
        assert!(artifact.hydration_keys.is_empty());
    }

    #[test]
    fn webui_constructor_starts_with_no_hydration_surface() {
        let artifact =
            ComponentTemplateArtifact::webui("x-b".into(), "{\"j\":1}".into(), "[]".into());
        assert_eq!(artifact.tag_name, "x-b");
        assert!(artifact.template.is_empty());
        assert_eq!(artifact.template_json, "{\"j\":1}");
        assert_eq!(artifact.template_functions, "[]");
        assert!(artifact.hydration_keys.is_empty());
    }

    #[test]
    fn with_hydration_keys_attaches_surface_fluently() {
        let artifact = ComponentTemplateArtifact::webui("x-c".into(), "{}".into(), "[]".into())
            .with_hydration_keys(vec!["count".into(), "name".into()]);
        assert_eq!(artifact.hydration_keys, vec!["count", "name"]);
    }

    #[test]
    fn with_hydration_keys_is_plugin_agnostic_over_template_payloads() {
        // A non-WebUI plugin payload can carry its own hydration surface too.
        let artifact = ComponentTemplateArtifact::template("x-d".into(), "<f-t></f-t>".into())
            .with_hydration_keys(vec!["value".into()]);
        assert_eq!(artifact.template, "<f-t></f-t>");
        assert_eq!(artifact.hydration_keys, vec!["value"]);
    }
}
