// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IpcFrame {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(fixed64, tag = "2")]
    pub generation: u64,
    #[prost(fixed64, tag = "3")]
    pub id: u64,
    #[prost(enumeration = "Kind", tag = "4")]
    pub kind: i32,
    #[prost(uint32, tag = "5")]
    pub method_id: u32,
    #[prost(uint32, tag = "6")]
    pub timeout_ms: u32,
    #[prost(oneof = "ipc_frame::Body", tags = "7, 8")]
    pub body: ::core::option::Option<ipc_frame::Body>,
}
/// Nested message and enum types in `IpcFrame`.
pub mod ipc_frame {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(bytes, tag = "7")]
        Payload(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "8")]
        Error(super::WireError),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WireError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub help: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub application_code: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Kind {
    Unspecified = 0,
    Request = 1,
    Result = 2,
    Error = 3,
    Notify = 4,
    Accept = 5,
    Cancel = 6,
}
impl Kind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "KIND_UNSPECIFIED",
            Self::Request => "REQUEST",
            Self::Result => "RESULT",
            Self::Error => "ERROR",
            Self::Notify => "NOTIFY",
            Self::Accept => "ACCEPT",
            Self::Cancel => "CANCEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "REQUEST" => Some(Self::Request),
            "RESULT" => Some(Self::Result),
            "ERROR" => Some(Self::Error),
            "NOTIFY" => Some(Self::Notify),
            "ACCEPT" => Some(Self::Accept),
            "CANCEL" => Some(Self::Cancel),
            _ => None,
        }
    }
}
