// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// @generated by webui-desktop-build. Do not edit.
use std::collections::BTreeMap;
use webui_desktop::ipc::{IpcCodec, IpcError, PayloadWriter, WireReader};
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Item {
pub id: u64,
pub image: Vec<u8>,
pub title: Option<String>,
pub minimum: i64,
pub status: i32,
pub scores: Vec<i32>,
pub labels: BTreeMap<String, String>,
pub enabled: Option<bool>,
pub chunks: BTreeMap<i32, Vec<u8>>,
pub metrics: Option<super::types::Metrics>,
pub flags: BTreeMap<bool, String>,
pub unsigned_keys: BTreeMap<u64, String>,
pub signed_keys: BTreeMap<i64, String>,
pub choice: Option<item::Choice>,
}
pub mod item { #[allow(unused_imports)] use super::*;
#[derive(Clone, Debug, PartialEq)]
pub enum Choice {
Text(String),
Number(i64),
}
}
impl IpcCodec for Item {
fn encode_ipc(&self) -> Vec<u8> { let mut writer = PayloadWriter::with_capacity(64);
if self.id != 0 { writer.uint64(1, self.id); }
if !self.image.is_empty() { writer.bytes(2, &self.image); }
if let Some(v) = &self.title { writer.string(3, v); }
if self.minimum != 0 { writer.int64(4, self.minimum); }
if self.status != 0 { writer.int32(5, self.status); }
if !self.scores.is_empty() { let mut packed = PayloadWriter::with_capacity(self.scores.len()); for v in &self.scores { packed.varint(((*v << 1) ^ (*v >> 31)) as u32 as u64); } writer.bytes(6, &packed.finish()); }
for (k, v) in &self.labels { let mut entry = PayloadWriter::with_capacity(32); if !k.is_empty() { entry.string(1, k); } if !v.is_empty() { entry.string(2, v); } writer.bytes(7, &entry.finish()); }
if let Some(item::Choice::Text(v)) = &self.choice { writer.string(8, v); }
if let Some(item::Choice::Number(v)) = &self.choice { writer.int64(9, *v); }
if let Some(v) = &self.enabled { writer.bool(11, *v); }
for (k, v) in &self.chunks { let mut entry = PayloadWriter::with_capacity(32); if *k != 0 { entry.int32(1, *k); } if !v.is_empty() { entry.bytes(2, v); } writer.bytes(12, &entry.finish()); }
if let Some(v) = &self.metrics { writer.bytes(13, &(v).encode_ipc()); }
for (k, v) in &self.flags { let mut entry = PayloadWriter::with_capacity(32); if *k { entry.bool(1, *k); } if !v.is_empty() { entry.string(2, v); } writer.bytes(14, &entry.finish()); }
for (k, v) in &self.unsigned_keys { let mut entry = PayloadWriter::with_capacity(32); if *k != 0 { entry.uint64(1, *k); } if !v.is_empty() { entry.string(2, v); } writer.bytes(15, &entry.finish()); }
for (k, v) in &self.signed_keys { let mut entry = PayloadWriter::with_capacity(32); if *k != 0 { entry.int64(1, *k); } if !v.is_empty() { entry.string(2, v); } writer.bytes(16, &entry.finish()); }
writer.finish() }
fn decode_ipc(bytes: &[u8]) -> Result<Self, IpcError> { let mut value = Self::default(); let mut reader = WireReader::new(bytes); while let Some(field) = reader.next_field()? { match field.number {
1 => { value.id = field.uint64()?; }
2 => { value.image = field.bytes()?.to_vec(); }
3 => { value.title = Some(field.string()?); }
4 => { value.minimum = field.int64()?; }
5 => { value.status = field.int32()?; }
6 => { if field.wire == 2 { let mut packed = WireReader::new(field.bytes()?); while !packed.is_empty() { value.scores.push({ let n = packed.varint()? as u32; ((n >> 1) as i32) ^ (-((n & 1) as i32)) }); } } else { value.scores.push(field.sint32()?); } }
7 => { let mut r = WireReader::new(field.bytes()?); let mut k = Default::default(); let mut v = Default::default(); while let Some(e) = r.next_field()? { match e.number { 1 => k = e.string()?, 2 => v = e.string()?, _ => {} } } value.labels.insert(k, v); }
8 => { value.choice = Some(item::Choice::Text(field.string()?)); }
9 => { value.choice = Some(item::Choice::Number(field.int64()?)); }
11 => { value.enabled = Some(field.bool()?); }
12 => { let mut r = WireReader::new(field.bytes()?); let mut k = Default::default(); let mut v = Default::default(); while let Some(e) = r.next_field()? { match e.number { 1 => k = e.int32()?, 2 => v = e.bytes()?.to_vec(), _ => {} } } value.chunks.insert(k, v); }
13 => { value.metrics = Some(IpcCodec::decode_ipc(field.bytes()?)?); }
14 => { let mut r = WireReader::new(field.bytes()?); let mut k = Default::default(); let mut v = Default::default(); while let Some(e) = r.next_field()? { match e.number { 1 => k = e.bool()?, 2 => v = e.string()?, _ => {} } } value.flags.insert(k, v); }
15 => { let mut r = WireReader::new(field.bytes()?); let mut k = Default::default(); let mut v = Default::default(); while let Some(e) = r.next_field()? { match e.number { 1 => k = e.uint64()?, 2 => v = e.string()?, _ => {} } } value.unsigned_keys.insert(k, v); }
16 => { let mut r = WireReader::new(field.bytes()?); let mut k = Default::default(); let mut v = Default::default(); while let Some(e) = r.next_field()? { match e.number { 1 => k = e.int64()?, 2 => v = e.string()?, _ => {} } } value.signed_keys.insert(k, v); }
_ => {}, } } Ok(value) }
}
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Label {
pub text: String,
}
impl IpcCodec for Label {
fn encode_ipc(&self) -> Vec<u8> { let mut writer = PayloadWriter::with_capacity(64);
if !self.text.is_empty() { writer.string(1, &self.text); }
writer.finish() }
fn decode_ipc(bytes: &[u8]) -> Result<Self, IpcError> { let mut value = Self::default(); let mut reader = WireReader::new(bytes); while let Some(field) = reader.next_field()? { match field.number {
1 => { value.text = field.string()?; }
_ => {}, } } Ok(value) }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(i32)]
pub enum Status {
Ready = 1,
Unspecified = 0,
}
