// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metrics {
    #[prost(double, tag = "1")]
    pub infinity: f64,
    #[prost(float, tag = "2")]
    pub not_a_number: f32,
    #[prost(fixed64, tag = "3")]
    pub maximum_fixed: u64,
    #[prost(sfixed64, tag = "4")]
    pub minimum_fixed: i64,
    #[prost(sint64, tag = "5")]
    pub minimum_zigzag: i64,
    #[prost(fixed32, tag = "6")]
    pub maximum_fixed32: u32,
    #[prost(sfixed32, tag = "7")]
    pub minimum_fixed32: i32,
    #[prost(uint32, tag = "8")]
    pub maximum_unsigned: u32,
    #[prost(int32, tag = "9")]
    pub minimum_signed: i32,
    #[prost(bool, tag = "10")]
    pub truth: bool,
    #[prost(message, repeated, tag = "11")]
    pub details: ::prost::alloc::vec::Vec<metrics::Detail>,
}
/// Nested message and enum types in `Metrics`.
pub mod metrics {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Detail {
        #[prost(string, tag = "1")]
        pub url_value: ::prost::alloc::string::String,
    }
}
