// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// @generated by webui-desktop-build. Do not edit.
use webui_desktop::ipc::{IpcCodec, IpcError, PayloadWriter, WireReader};
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Metrics {
pub infinity: f64,
pub not_a_number: f32,
pub maximum_fixed: u64,
pub minimum_fixed: i64,
pub minimum_zigzag: i64,
pub maximum_fixed32: u32,
pub minimum_fixed32: i32,
pub maximum_unsigned: u32,
pub minimum_signed: i32,
pub truth: bool,
pub details: Vec<metrics::Detail>,
}
pub mod metrics { #[allow(unused_imports)] use super::*;
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Detail {
pub url_value: String,
}
impl IpcCodec for Detail {
fn encode_ipc(&self) -> Vec<u8> { let mut writer = PayloadWriter::with_capacity(64);
if !self.url_value.is_empty() { writer.string(1, &self.url_value); }
writer.finish() }
fn decode_ipc(bytes: &[u8]) -> Result<Self, IpcError> { let mut value = Self::default(); let mut reader = WireReader::new(bytes); while let Some(field) = reader.next_field()? { match field.number {
1 => { value.url_value = field.string()?; }
_ => {}, } } Ok(value) }
}
}
impl IpcCodec for Metrics {
fn encode_ipc(&self) -> Vec<u8> { let mut writer = PayloadWriter::with_capacity(64);
if self.infinity != 0.0 { writer.double(1, self.infinity); }
if self.not_a_number != 0.0 { writer.float(2, self.not_a_number); }
if self.maximum_fixed != 0 { writer.fixed64(3, self.maximum_fixed); }
if self.minimum_fixed != 0 { writer.sfixed64(4, self.minimum_fixed); }
if self.minimum_zigzag != 0 { writer.sint64(5, self.minimum_zigzag); }
if self.maximum_fixed32 != 0 { writer.fixed32(6, self.maximum_fixed32); }
if self.minimum_fixed32 != 0 { writer.sfixed32(7, self.minimum_fixed32); }
if self.maximum_unsigned != 0 { writer.uint32(8, self.maximum_unsigned); }
if self.minimum_signed != 0 { writer.int32(9, self.minimum_signed); }
if self.truth { writer.bool(10, self.truth); }
for v in &self.details { writer.bytes(11, &(v).encode_ipc()); }
writer.finish() }
fn decode_ipc(bytes: &[u8]) -> Result<Self, IpcError> { let mut value = Self::default(); let mut reader = WireReader::new(bytes); while let Some(field) = reader.next_field()? { match field.number {
1 => { value.infinity = field.double()?; }
2 => { value.not_a_number = field.float()?; }
3 => { value.maximum_fixed = field.fixed64()?; }
4 => { value.minimum_fixed = field.sfixed64()?; }
5 => { value.minimum_zigzag = field.sint64()?; }
6 => { value.maximum_fixed32 = field.fixed32()?; }
7 => { value.minimum_fixed32 = field.sfixed32()?; }
8 => { value.maximum_unsigned = field.uint32()?; }
9 => { value.minimum_signed = field.int32()?; }
10 => { value.truth = field.bool()?; }
11 => { value.details.push(IpcCodec::decode_ipc(field.bytes()?)?); }
_ => {}, } } Ok(value) }
}
