// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Item {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub image: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag = "3")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, tag = "4")]
    pub minimum: i64,
    #[prost(enumeration = "Status", tag = "5")]
    pub status: i32,
    #[prost(sint32, repeated, tag = "6")]
    pub scores: ::prost::alloc::vec::Vec<i32>,
    #[prost(btree_map = "string, string", tag = "7")]
    pub labels: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(btree_map = "int32, bytes", tag = "12")]
    pub chunks: ::prost::alloc::collections::BTreeMap<i32, ::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, optional, tag = "11")]
    pub enabled: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "13")]
    pub metrics: ::core::option::Option<super::types::Metrics>,
    #[prost(btree_map = "bool, string", tag = "14")]
    pub flags: ::prost::alloc::collections::BTreeMap<
        bool,
        ::prost::alloc::string::String,
    >,
    #[prost(btree_map = "uint64, string", tag = "15")]
    pub unsigned_keys: ::prost::alloc::collections::BTreeMap<
        u64,
        ::prost::alloc::string::String,
    >,
    #[prost(btree_map = "int64, string", tag = "16")]
    pub signed_keys: ::prost::alloc::collections::BTreeMap<
        i64,
        ::prost::alloc::string::String,
    >,
    #[prost(oneof = "item::Choice", tags = "8, 9")]
    pub choice: ::core::option::Option<item::Choice>,
}
/// Nested message and enum types in `Item`.
pub mod item {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Choice {
        #[prost(string, tag = "8")]
        Text(::prost::alloc::string::String),
        #[prost(int64, tag = "9")]
        Number(i64),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Label {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Status {
    Unspecified = 0,
    Ready = 1,
}
impl Status {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STATUS_UNSPECIFIED",
            Self::Ready => "READY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "READY" => Some(Self::Ready),
            _ => None,
        }
    }
}
