// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// @generated by webui-desktop-build. Do not edit.
pub mod messages { include!("ipc_messages.rs"); }
use webui_desktop::ipc::*;
pub const SCHEMA_HASH: &str = "92ed62d2af279faa6246ab76b7a6290e22b17cbd9364725af433373599a6837b";
pub static MESSAGE_SHAPES: &[MessageShape] = &[
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::Uint64, repeated: false, oneof: None, map_key: false },
FieldShape { number: 2, kind: FieldKind::Bytes, repeated: false, oneof: None, map_key: false },
FieldShape { number: 3, kind: FieldKind::String, repeated: false, oneof: None, map_key: false },
FieldShape { number: 4, kind: FieldKind::Int64, repeated: false, oneof: None, map_key: false },
FieldShape { number: 5, kind: FieldKind::Enum, repeated: false, oneof: None, map_key: false },
FieldShape { number: 6, kind: FieldKind::Sint32, repeated: true, oneof: None, map_key: false },
FieldShape { number: 7, kind: FieldKind::Message(3), repeated: true, oneof: None, map_key: false },
FieldShape { number: 8, kind: FieldKind::String, repeated: false, oneof: Some(0), map_key: false },
FieldShape { number: 9, kind: FieldKind::Int64, repeated: false, oneof: Some(0), map_key: false },
FieldShape { number: 11, kind: FieldKind::Bool, repeated: false, oneof: None, map_key: false },
FieldShape { number: 12, kind: FieldKind::Message(1), repeated: true, oneof: None, map_key: false },
FieldShape { number: 13, kind: FieldKind::Message(7), repeated: false, oneof: None, map_key: false },
FieldShape { number: 14, kind: FieldKind::Message(2), repeated: true, oneof: None, map_key: false },
FieldShape { number: 15, kind: FieldKind::Message(5), repeated: true, oneof: None, map_key: false },
FieldShape { number: 16, kind: FieldKind::Message(4), repeated: true, oneof: None, map_key: false },
] },
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::Int32, repeated: false, oneof: None, map_key: true },
FieldShape { number: 2, kind: FieldKind::Bytes, repeated: false, oneof: None, map_key: false },
] },
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::Bool, repeated: false, oneof: None, map_key: true },
FieldShape { number: 2, kind: FieldKind::String, repeated: false, oneof: None, map_key: false },
] },
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::String, repeated: false, oneof: None, map_key: true },
FieldShape { number: 2, kind: FieldKind::String, repeated: false, oneof: None, map_key: false },
] },
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::Int64, repeated: false, oneof: None, map_key: true },
FieldShape { number: 2, kind: FieldKind::String, repeated: false, oneof: None, map_key: false },
] },
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::Uint64, repeated: false, oneof: None, map_key: true },
FieldShape { number: 2, kind: FieldKind::String, repeated: false, oneof: None, map_key: false },
] },
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::String, repeated: false, oneof: None, map_key: false },
] },
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::Double, repeated: false, oneof: None, map_key: false },
FieldShape { number: 2, kind: FieldKind::Float, repeated: false, oneof: None, map_key: false },
FieldShape { number: 3, kind: FieldKind::Fixed64, repeated: false, oneof: None, map_key: false },
FieldShape { number: 4, kind: FieldKind::Sfixed64, repeated: false, oneof: None, map_key: false },
FieldShape { number: 5, kind: FieldKind::Sint64, repeated: false, oneof: None, map_key: false },
FieldShape { number: 6, kind: FieldKind::Fixed32, repeated: false, oneof: None, map_key: false },
FieldShape { number: 7, kind: FieldKind::Sfixed32, repeated: false, oneof: None, map_key: false },
FieldShape { number: 8, kind: FieldKind::Uint32, repeated: false, oneof: None, map_key: false },
FieldShape { number: 9, kind: FieldKind::Int32, repeated: false, oneof: None, map_key: false },
FieldShape { number: 10, kind: FieldKind::Bool, repeated: false, oneof: None, map_key: false },
FieldShape { number: 11, kind: FieldKind::Message(8), repeated: true, oneof: None, map_key: false },
] },
MessageShape { fields: &[
FieldShape { number: 1, kind: FieldKind::String, repeated: false, oneof: None, map_key: false },
] },
MessageShape { fields: &[
] },
];
fn validate_0(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 0, MESSAGE_SHAPES, limits) }
fn validate_1(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 1, MESSAGE_SHAPES, limits) }
fn validate_2(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 2, MESSAGE_SHAPES, limits) }
fn validate_3(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 3, MESSAGE_SHAPES, limits) }
fn validate_4(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 4, MESSAGE_SHAPES, limits) }
fn validate_5(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 5, MESSAGE_SHAPES, limits) }
fn validate_6(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 6, MESSAGE_SHAPES, limits) }
fn validate_7(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 7, MESSAGE_SHAPES, limits) }
fn validate_8(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 8, MESSAGE_SHAPES, limits) }
fn validate_9(bytes: &[u8], limits: &IpcLimits) -> Result<(), IpcError> { validate_message(bytes, 9, MESSAGE_SHAPES, limits) }
pub static SCHEMA: IpcSchema = IpcSchema { name: "example.desktop", major: 1, hash: SCHEMA_HASH, methods: &[
MethodDescriptor { id: 1101, name: "example.desktop.Host.Save", receiver: Endpoint::Host, kind: MethodKind::Rpc, development_only: false, validate_request: validate_0, validate_response: Some(validate_9) },
MethodDescriptor { id: 1102, name: "example.desktop.Host.Selected", receiver: Endpoint::Host, kind: MethodKind::Notification, development_only: false, validate_request: validate_0, validate_response: None },
MethodDescriptor { id: 2001, name: "example.desktop.Renderer.LabelFor", receiver: Endpoint::Renderer, kind: MethodKind::Rpc, development_only: false, validate_request: validate_0, validate_response: Some(validate_6) },
MethodDescriptor { id: 2002, name: "example.desktop.Renderer.Changed", receiver: Endpoint::Renderer, kind: MethodKind::Notification, development_only: false, validate_request: validate_0, validate_response: None },
] };
pub mod host { use super::*;
#[derive(Debug, Clone, Copy)] pub struct Save;
impl Rpc for Save { type Request = messages::example::desktop::Item; type Response = (); type Receiver = Host; const ID: u32 = 1101; }
#[derive(Debug, Clone, Copy)] pub struct Selected;
impl Event for Selected { type Payload = messages::example::desktop::Item; type Receiver = Host; const ID: u32 = 1102; }
pub fn subscribe_selected<F, Fut>(session: &IpcSession, callback: F) -> Result<IpcSubscription, IpcError> where F: Fn(NotificationContext, messages::example::desktop::Item) -> Fut + Send + Sync + 'static, Fut: std::future::Future<Output = Result<(), IpcError>> + Send + 'static { session.subscribe::<Selected, F, Fut>(callback) }
}
pub trait HostHandler: Send + Sync + 'static {
fn save(&self, context: RequestContext, request: messages::example::desktop::Item) -> IpcFuture<()>;
fn selected(&self, context: NotificationContext, request: messages::example::desktop::Item) -> IpcFuture<()>;
}
pub fn register_host(registry: &mut IpcRegistry, handler: std::sync::Arc<dyn HostHandler>) -> Result<(), IpcError> {
registry.validate_registration(&[1101,1102,])?;
{ let handler = std::sync::Arc::clone(&handler); registry.register::<host::Save, _, _>(move |context, request| handler.save(context, request))?; }
{ let handler = std::sync::Arc::clone(&handler); registry.register_notification::<host::Selected, _, _>(move |context, request| handler.selected(context, request))?; }
Ok(()) }
pub mod renderer { use super::*;
#[derive(Debug, Clone, Copy)] pub struct LabelFor;
impl Rpc for LabelFor { type Request = messages::example::desktop::Item; type Response = messages::example::desktop::Label; type Receiver = Renderer; const ID: u32 = 2001; }
#[derive(Debug, Clone, Copy)] pub struct Changed;
impl Event for Changed { type Payload = messages::example::desktop::Item; type Receiver = Renderer; const ID: u32 = 2002; }
}
#[derive(Clone)] pub struct RendererClient { session: IpcSession }
impl RendererClient { pub fn new(session: IpcSession) -> Self { Self { session } }
pub fn label_for(&self, request: messages::example::desktop::Item, options: CallOptions) -> IpcCall<messages::example::desktop::Label> { self.session.call::<renderer::LabelFor>(request, options) }
pub fn changed(&self, payload: messages::example::desktop::Item) -> IpcFuture<()> { self.session.notify::<renderer::Changed>(payload) }
}
