// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// @generated by webui-desktop-build. Do not edit.
pub mod example {
pub mod desktop {
include!("example.desktop.rs");
}
pub mod types {
include!("example.types.rs");
}
}
