// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// This file is @generated by prost-build.
pub mod example {
    pub mod desktop {
        include!("example.desktop.rs");
    }
    pub mod types {
        include!("example.types.rs");
    }
}
