// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// @generated by webui-desktop-build. Do not edit.
import { BoundaryReader, PayloadWriter, readDelimited, readUint32, readUint64, skipField, IpcError } from '@microsoft/webui-desktop';
import { Metrics } from './types.js';
export type Status = number;
export const Status = {
READY: 1,
statusUnspecified: 0,
} as const;
export interface Item {
id: bigint;
image: Uint8Array;
title?: string;
minimum: bigint;
status: number;
scores: number[];
labels: Map<string, string>;
enabled?: boolean;
chunks: Map<number, Uint8Array>;
metrics?: Metrics;
flags: Map<boolean, string>;
unsignedKeys: Map<bigint, string>;
signedKeys: Map<bigint, string>;
choice?: { $case: "text"; value: string } | { $case: "number"; value: bigint };
}
export interface Label {
text: string;
}
function createBaseItem(): Item { return {
id: 0n,
image: new Uint8Array(0),
title: undefined,
minimum: 0n,
status: 0,
scores: [],
labels: new Map(),
enabled: undefined,
chunks: new Map(),
metrics: undefined,
flags: new Map(),
unsignedKeys: new Map(),
signedKeys: new Map(),
choice: undefined,
}; }
export const Item = {
encode(message: Item): Uint8Array { const writer = new PayloadWriter();
if (message.id !== 0n) { writer.uint64(1, message.id); }
if (message.image.byteLength !== 0) { writer.bytesField(2, message.image); }
if (message.title !== undefined) { writer.string(3, message.title); }
if (message.minimum !== 0n) { writer.int64(4, message.minimum); }
if (message.status !== 0) { writer.enum(5, message.status); }
for (const value of message.scores) { writer.sint32(6, value); }
for (const [key, value] of message.labels) { const entry = new PayloadWriter(); if (key !== "") { entry.string(1, key); } if (value !== "") { entry.string(2, value); } writer.bytesField(7, entry.finish()); }
if (message.choice?.$case === "text") { const value = message.choice.value; writer.string(8, value); }
if (message.choice?.$case === "number") { const value = message.choice.value; writer.int64(9, value); }
if (message.enabled !== undefined) { writer.bool(11, message.enabled); }
for (const [key, value] of message.chunks) { const entry = new PayloadWriter(); if (key !== 0) { entry.int32(1, key); } if (value.byteLength !== 0) { entry.bytesField(2, value); } writer.bytesField(12, entry.finish()); }
if (message.metrics !== undefined) { writer.bytesField(13, Metrics.encode(message.metrics)); }
for (const [key, value] of message.flags) { const entry = new PayloadWriter(); if (key) { entry.bool(1, key); } if (value !== "") { entry.string(2, value); } writer.bytesField(14, entry.finish()); }
for (const [key, value] of message.unsignedKeys) { const entry = new PayloadWriter(); if (key !== 0n) { entry.uint64(1, key); } if (value !== "") { entry.string(2, value); } writer.bytesField(15, entry.finish()); }
for (const [key, value] of message.signedKeys) { const entry = new PayloadWriter(); if (key !== 0n) { entry.int64(1, key); } if (value !== "") { entry.string(2, value); } writer.bytesField(16, entry.finish()); }
return writer.finish(); },
decode(bytes: Uint8Array): Item { const reader = new BoundaryReader(bytes); const message = createBaseItem(); while (reader.pos < reader.len) { const [number, type] = reader.tag(); switch (number) {
case 1: { message.id = readUint64(reader); break; }
case 2: { message.image = new Uint8Array(readDelimited(reader)); break; }
case 3: { message.title = new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(reader)); break; }
case 4: { message.minimum = BigInt.asIntN(64, readUint64(reader)); break; }
case 5: { message.status = Number(BigInt.asIntN(32, readUint64(reader))); break; }
case 6: { if (type === 2) { const packed = new BoundaryReader(readDelimited(reader)); while (packed.pos < packed.len) message.scores.push((() => { const raw = readUint32(packed); return ((raw >>> 1) ^ -(raw & 1)); })()); } else { message.scores.push((() => { const raw = readUint32(reader); return ((raw >>> 1) ^ -(raw & 1)); })()); } break; }
case 7: { const entry = new BoundaryReader(readDelimited(reader)); let key = ""; let value = ""; while (entry.pos < entry.len) { const [entryNumber, entryType] = entry.tag(); switch (entryNumber) { case 1: key = new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(entry)); break; case 2: value = new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(entry)); break; default: skipField(entry, entryType); break; } } message.labels.set(key, value); break; }
case 8: { message.choice = { $case: "text", value: new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(reader)) }; break; }
case 9: { message.choice = { $case: "number", value: BigInt.asIntN(64, readUint64(reader)) }; break; }
case 11: { message.enabled = readUint32(reader) === 1; break; }
case 12: { const entry = new BoundaryReader(readDelimited(reader)); let key = 0; let value = new Uint8Array(0); while (entry.pos < entry.len) { const [entryNumber, entryType] = entry.tag(); switch (entryNumber) { case 1: key = Number(BigInt.asIntN(32, readUint64(entry))); break; case 2: value = new Uint8Array(readDelimited(entry)); break; default: skipField(entry, entryType); break; } } message.chunks.set(key, value); break; }
case 13: { message.metrics = Metrics.decode(readDelimited(reader)); break; }
case 14: { const entry = new BoundaryReader(readDelimited(reader)); let key = false; let value = ""; while (entry.pos < entry.len) { const [entryNumber, entryType] = entry.tag(); switch (entryNumber) { case 1: key = readUint32(entry) === 1; break; case 2: value = new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(entry)); break; default: skipField(entry, entryType); break; } } message.flags.set(key, value); break; }
case 15: { const entry = new BoundaryReader(readDelimited(reader)); let key = 0n; let value = ""; while (entry.pos < entry.len) { const [entryNumber, entryType] = entry.tag(); switch (entryNumber) { case 1: key = readUint64(entry); break; case 2: value = new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(entry)); break; default: skipField(entry, entryType); break; } } message.unsignedKeys.set(key, value); break; }
case 16: { const entry = new BoundaryReader(readDelimited(reader)); let key = 0n; let value = ""; while (entry.pos < entry.len) { const [entryNumber, entryType] = entry.tag(); switch (entryNumber) { case 1: key = BigInt.asIntN(64, readUint64(entry)); break; case 2: value = new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(entry)); break; default: skipField(entry, entryType); break; } } message.signedKeys.set(key, value); break; }
default: skipField(reader, type); break; } } return message; }
};
function createBaseLabel(): Label { return {
text: "",
}; }
export const Label = {
encode(message: Label): Uint8Array { const writer = new PayloadWriter();
if (message.text !== "") { writer.string(1, message.text); }
return writer.finish(); },
decode(bytes: Uint8Array): Label { const reader = new BoundaryReader(bytes); const message = createBaseLabel(); while (reader.pos < reader.len) { const [number, type] = reader.tag(); switch (number) {
case 1: { message.text = new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(reader)); break; }
default: skipField(reader, type); break; } } return message; }
};
