// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: application.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Metrics } from "./types.js";

export const protobufPackage = "example.desktop";

export enum Status {
  STATUS_UNSPECIFIED = 0,
  READY = 1,
  UNRECOGNIZED = -1,
}

export interface Item {
  id: bigint;
  image: Uint8Array;
  title?: string | undefined;
  minimum: bigint;
  status: Status;
  scores: number[];
  labels: Map<string, string>;
  choice?: { $case: "text"; value: string } | { $case: "number"; value: bigint } | undefined;
  chunks: Map<number, Uint8Array>;
  enabled?: boolean | undefined;
  metrics?: Metrics | undefined;
  flags: Map<boolean, string>;
  unsignedKeys: Map<bigint, string>;
  signedKeys: Map<bigint, string>;
}

export interface Item_LabelsEntry {
  key: string;
  value: string;
}

export interface Item_ChunksEntry {
  key: number;
  value: Uint8Array;
}

export interface Item_FlagsEntry {
  key: boolean;
  value: string;
}

export interface Item_UnsignedKeysEntry {
  key: bigint;
  value: string;
}

export interface Item_SignedKeysEntry {
  key: bigint;
  value: string;
}

export interface Label {
  text: string;
}

function createBaseItem(): Item {
  return {
    id: 0n,
    image: new Uint8Array(0),
    title: undefined,
    minimum: 0n,
    status: 0,
    scores: [],
    labels: new Map(),
    choice: undefined,
    chunks: new Map(),
    enabled: undefined,
    metrics: undefined,
    flags: new Map(),
    unsignedKeys: new Map(),
    signedKeys: new Map(),
  };
}

export const Item: MessageFns<Item> = {
  encode(message: Item, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0n) {
      if (BigInt.asUintN(64, message.id) !== message.id) {
        throw new globalThis.Error("value provided for field message.id of type uint64 too large");
      }
      writer.uint32(8).uint64(message.id);
    }
    if (message.image.length !== 0) {
      writer.uint32(18).bytes(message.image);
    }
    if (message.title !== undefined) {
      writer.uint32(26).string(message.title);
    }
    if (message.minimum !== 0n) {
      if (BigInt.asIntN(64, message.minimum) !== message.minimum) {
        throw new globalThis.Error("value provided for field message.minimum of type int64 too large");
      }
      writer.uint32(32).int64(message.minimum);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    writer.uint32(50).fork();
    for (const v of message.scores) {
      writer.sint32(v);
    }
    writer.join();
    message.labels.forEach((value, key) => {
      Item_LabelsEntry.encode({ key: key as any, value }, writer.uint32(58).fork()).join();
    });
    switch (message.choice?.$case) {
      case "text":
        writer.uint32(66).string(message.choice.value);
        break;
      case "number":
        if (BigInt.asIntN(64, message.choice.value) !== message.choice.value) {
          throw new globalThis.Error("value provided for field message.choice.value of type int64 too large");
        }
        writer.uint32(72).int64(message.choice.value);
        break;
    }
    message.chunks.forEach((value, key) => {
      Item_ChunksEntry.encode({ key: key as any, value }, writer.uint32(98).fork()).join();
    });
    if (message.enabled !== undefined) {
      writer.uint32(88).bool(message.enabled);
    }
    if (message.metrics !== undefined) {
      Metrics.encode(message.metrics, writer.uint32(106).fork()).join();
    }
    message.flags.forEach((value, key) => {
      Item_FlagsEntry.encode({ key: key as any, value }, writer.uint32(114).fork()).join();
    });
    message.unsignedKeys.forEach((value, key) => {
      Item_UnsignedKeysEntry.encode({ key: key as any, value }, writer.uint32(122).fork()).join();
    });
    message.signedKeys.forEach((value, key) => {
      Item_SignedKeysEntry.encode({ key: key as any, value }, writer.uint32(130).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseItem();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.id = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.image = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.title = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.minimum = reader.int64() as bigint;
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.status = reader.int32() as any;
            continue;
          }
          case 6: {
            if (tag === 48) {
              message.scores.push(reader.sint32());

              continue;
            }

            if (tag === 50) {
              const end2 = reader.uint32() + reader.pos;
              while (reader.pos < end2) {
                message.scores.push(reader.sint32());
              }

              continue;
            }

            break;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            const entry7 = Item_LabelsEntry.decode(reader, reader.uint32());
            if (entry7.value !== undefined) {
              message.labels.set(entry7.key, entry7.value);
            }
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.choice = { $case: "text", value: reader.string() };
            continue;
          }
          case 9: {
            if (tag !== 72) {
              break;
            }

            message.choice = { $case: "number", value: reader.int64() as bigint };
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            const entry12 = Item_ChunksEntry.decode(reader, reader.uint32());
            if (entry12.value !== undefined) {
              message.chunks.set(entry12.key, entry12.value);
            }
            continue;
          }
          case 11: {
            if (tag !== 88) {
              break;
            }

            message.enabled = reader.bool();
            continue;
          }
          case 13: {
            if (tag !== 106) {
              break;
            }

            message.metrics = Metrics.decode(reader, reader.uint32());
            continue;
          }
          case 14: {
            if (tag !== 114) {
              break;
            }

            const entry14 = Item_FlagsEntry.decode(reader, reader.uint32());
            if (entry14.value !== undefined) {
              message.flags.set(entry14.key, entry14.value);
            }
            continue;
          }
          case 15: {
            if (tag !== 122) {
              break;
            }

            const entry15 = Item_UnsignedKeysEntry.decode(reader, reader.uint32());
            if (entry15.value !== undefined) {
              message.unsignedKeys.set(entry15.key, entry15.value);
            }
            continue;
          }
          case 16: {
            if (tag !== 130) {
              break;
            }

            const entry16 = Item_SignedKeysEntry.decode(reader, reader.uint32());
            if (entry16.value !== undefined) {
              message.signedKeys.set(entry16.key, entry16.value);
            }
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

function createBaseItem_LabelsEntry(): Item_LabelsEntry {
  return { key: "", value: "" };
}

export const Item_LabelsEntry: MessageFns<Item_LabelsEntry> = {
  encode(message: Item_LabelsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_LabelsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseItem_LabelsEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

function createBaseItem_ChunksEntry(): Item_ChunksEntry {
  return { key: 0, value: new Uint8Array(0) };
}

export const Item_ChunksEntry: MessageFns<Item_ChunksEntry> = {
  encode(message: Item_ChunksEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value.length !== 0) {
      writer.uint32(18).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_ChunksEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseItem_ChunksEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.key = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

function createBaseItem_FlagsEntry(): Item_FlagsEntry {
  return { key: false, value: "" };
}

export const Item_FlagsEntry: MessageFns<Item_FlagsEntry> = {
  encode(message: Item_FlagsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== false) {
      writer.uint32(8).bool(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_FlagsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseItem_FlagsEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.key = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

function createBaseItem_UnsignedKeysEntry(): Item_UnsignedKeysEntry {
  return { key: 0n, value: "" };
}

export const Item_UnsignedKeysEntry: MessageFns<Item_UnsignedKeysEntry> = {
  encode(message: Item_UnsignedKeysEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0n) {
      if (BigInt.asUintN(64, message.key) !== message.key) {
        throw new globalThis.Error("value provided for field message.key of type uint64 too large");
      }
      writer.uint32(8).uint64(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_UnsignedKeysEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseItem_UnsignedKeysEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.key = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

function createBaseItem_SignedKeysEntry(): Item_SignedKeysEntry {
  return { key: 0n, value: "" };
}

export const Item_SignedKeysEntry: MessageFns<Item_SignedKeysEntry> = {
  encode(message: Item_SignedKeysEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0n) {
      if (BigInt.asIntN(64, message.key) !== message.key) {
        throw new globalThis.Error("value provided for field message.key of type int64 too large");
      }
      writer.uint32(8).int64(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Item_SignedKeysEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseItem_SignedKeysEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.key = reader.int64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

function createBaseLabel(): Label {
  return { text: "" };
}

export const Label: MessageFns<Label> = {
  encode(message: Label, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Label {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLabel();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.text = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
