// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// @generated by webui-desktop-build. Do not edit.
// Private implementation: application code imports ./ipc.js instead.
import type { AppConnection, RendererHandlers } from './ipc.js';
import { connect, validateMessage, validateValue, IpcError, type MessageShape, type MessageCodec, type ConnectionSchema, type RuntimeConnection, type IpcTransport, type RequestContext } from '@microsoft/webui-desktop';
import * as codec_0 from "./application.js";
import * as codec_1 from "./types.js";
export const schemaHash = "92ed62d2af279faa6246ab76b7a6290e22b17cbd9364725af433373599a6837b";
export const messageShapes: readonly MessageShape[] = [
{ fields: [
{ number: 1, name: "id", kind: "uint64", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 2, name: "image", kind: "bytes", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 3, name: "title", kind: "string", repeated: false, packed: false, optional: true, mapKey: false, map: false },
{ number: 4, name: "minimum", kind: "int64", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 5, name: "status", kind: "enum", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 6, name: "scores", kind: "sint32", repeated: true, packed: true, optional: false, mapKey: false, map: false },
{ number: 7, name: "labels", kind: "message", message: 3, repeated: true, packed: false, optional: false, mapKey: false, map: true },
{ number: 8, name: "text", kind: "string", repeated: false, packed: false, optional: true, mapKey: false, map: false, oneof: "choice" },
{ number: 9, name: "number", kind: "int64", repeated: false, packed: false, optional: true, mapKey: false, map: false, oneof: "choice" },
{ number: 11, name: "enabled", kind: "bool", repeated: false, packed: false, optional: true, mapKey: false, map: false },
{ number: 12, name: "chunks", kind: "message", message: 1, repeated: true, packed: false, optional: false, mapKey: false, map: true },
{ number: 13, name: "metrics", kind: "message", message: 7, repeated: false, packed: false, optional: true, mapKey: false, map: false },
{ number: 14, name: "flags", kind: "message", message: 2, repeated: true, packed: false, optional: false, mapKey: false, map: true },
{ number: 15, name: "unsignedKeys", kind: "message", message: 5, repeated: true, packed: false, optional: false, mapKey: false, map: true },
{ number: 16, name: "signedKeys", kind: "message", message: 4, repeated: true, packed: false, optional: false, mapKey: false, map: true },
] },
{ fields: [
{ number: 1, name: "key", kind: "int32", repeated: false, packed: false, optional: false, mapKey: true, map: false },
{ number: 2, name: "value", kind: "bytes", repeated: false, packed: false, optional: false, mapKey: false, map: false },
] },
{ fields: [
{ number: 1, name: "key", kind: "bool", repeated: false, packed: false, optional: false, mapKey: true, map: false },
{ number: 2, name: "value", kind: "string", repeated: false, packed: false, optional: false, mapKey: false, map: false },
] },
{ fields: [
{ number: 1, name: "key", kind: "string", repeated: false, packed: false, optional: false, mapKey: true, map: false },
{ number: 2, name: "value", kind: "string", repeated: false, packed: false, optional: false, mapKey: false, map: false },
] },
{ fields: [
{ number: 1, name: "key", kind: "int64", repeated: false, packed: false, optional: false, mapKey: true, map: false },
{ number: 2, name: "value", kind: "string", repeated: false, packed: false, optional: false, mapKey: false, map: false },
] },
{ fields: [
{ number: 1, name: "key", kind: "uint64", repeated: false, packed: false, optional: false, mapKey: true, map: false },
{ number: 2, name: "value", kind: "string", repeated: false, packed: false, optional: false, mapKey: false, map: false },
] },
{ fields: [
{ number: 1, name: "text", kind: "string", repeated: false, packed: false, optional: false, mapKey: false, map: false },
] },
{ fields: [
{ number: 1, name: "infinity", kind: "double", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 2, name: "notANumber", kind: "float", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 3, name: "maximumFixed", kind: "fixed64", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 4, name: "minimumFixed", kind: "sfixed64", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 5, name: "minimumZigzag", kind: "sint64", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 6, name: "maximumFixed32", kind: "fixed32", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 7, name: "minimumFixed32", kind: "sfixed32", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 8, name: "maximumUnsigned", kind: "uint32", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 9, name: "minimumSigned", kind: "int32", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 10, name: "truth", kind: "bool", repeated: false, packed: false, optional: false, mapKey: false, map: false },
{ number: 11, name: "details", kind: "message", message: 8, repeated: true, packed: false, optional: false, mapKey: false, map: false },
] },
{ fields: [
{ number: 1, name: "URLValue", kind: "string", repeated: false, packed: false, optional: false, mapKey: false, map: false },
] },
{ fields: [
] },
];
const message_0: MessageCodec<codec_0.Item> = {
encode: value => codec_0.Item.encode(value), decode: bytes => codec_0.Item.decode(bytes),
validate: (value, limits) => validateValue(value, 0, messageShapes, limits),
validateBytes: (bytes, limits) => validateMessage(bytes, 0, messageShapes, limits),
};
const message_6: MessageCodec<codec_0.Label> = {
encode: value => codec_0.Label.encode(value), decode: bytes => codec_0.Label.decode(bytes),
validate: (value, limits) => validateValue(value, 6, messageShapes, limits),
validateBytes: (bytes, limits) => validateMessage(bytes, 6, messageShapes, limits),
};
const message_7: MessageCodec<codec_1.Metrics> = {
encode: value => codec_1.Metrics.encode(value), decode: bytes => codec_1.Metrics.decode(bytes),
validate: (value, limits) => validateValue(value, 7, messageShapes, limits),
validateBytes: (bytes, limits) => validateMessage(bytes, 7, messageShapes, limits),
};
const message_8: MessageCodec<codec_1.Metrics_Detail> = {
encode: value => codec_1.Metrics_Detail.encode(value), decode: bytes => codec_1.Metrics_Detail.decode(bytes),
validate: (value, limits) => validateValue(value, 8, messageShapes, limits),
validateBytes: (bytes, limits) => validateMessage(bytes, 8, messageShapes, limits),
};
const message_9: MessageCodec<void> = {
encode: () => new Uint8Array(0), decode: bytes => { if (bytes.byteLength !== 0) throw new IpcError('invalid-payload', 'Empty requires empty bytes'); },
validate: value => { if (value !== undefined) throw new IpcError('invalid-payload', 'Empty requires undefined'); },
validateBytes: (bytes, limits) => validateMessage(bytes, 9, messageShapes, limits),
};
export const schema: ConnectionSchema = { hello: { wireVersion: 3, contractName: "example.desktop", contractMajor: 1, schemaHash }, methods: [
{ id: 1101, name: "example.desktop.Host.Save", receiver: "host", kind: "rpc", developmentOnly: false, request: message_0, response: message_9 },
{ id: 1102, name: "example.desktop.Host.Selected", receiver: "host", kind: "notification", developmentOnly: false, request: message_0 },
{ id: 2001, name: "example.desktop.Renderer.LabelFor", receiver: "renderer", kind: "rpc", developmentOnly: false, request: message_0, response: message_6 },
{ id: 2002, name: "example.desktop.Renderer.Changed", receiver: "renderer", kind: "notification", developmentOnly: false, request: message_0 },
] };
function handlersMap(handlers: RendererHandlers): ReadonlyMap<number, (value: any, context: RequestContext) => any> {
if (!handlers || typeof handlers !== 'object') throw new IpcError('invalid-payload', 'Renderer handlers must be an object');
if (typeof handlers.labelFor !== 'function') throw new IpcError('invalid-payload', 'Missing renderer handler: labelFor');
return new Map<number, (value: any, context: RequestContext) => any>([
[2001, (value, context) => handlers.labelFor(value, context)],
]);
}
export async function connectDesktop(transport: IpcTransport, options?: { renderer?: RendererHandlers; onError?: (error: IpcError) => void }): Promise<AppConnection> {
const connection: RuntimeConnection = await connect(transport, schema, { ...(options?.renderer ? { handlers: handlersMap(options.renderer) } : {}), ...(options?.onError ? { onError: options.onError } : {}) });
return { close: () => connection.close(), closed: connection.closed, setRenderer: handlers => connection.register(handlersMap(handlers)), host: {
save: (request, options) => connection.call(1101, request, options),
selected: request => connection.notify(1102, request),
}, renderer: {
onChanged: callback => connection.subscribe(2002, callback),
} };
}
