// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// @generated by webui-desktop-build. Do not edit.
import type { IpcError, IpcTransport, CallOptions, RequestContext, Subscription, DesktopConnection } from '@microsoft/webui-desktop';
import type * as codec_0 from "./application.js";
import type * as codec_1 from "./types.js";
export const schemaHash = "92ed62d2af279faa6246ab76b7a6290e22b17cbd9364725af433373599a6837b";
export interface HostClient {
save(request: codec_0.Item, options?: CallOptions): Promise<void>;
selected(request: codec_0.Item): Promise<void>;
}
export interface RendererHandlers {
labelFor(request: codec_0.Item, context: RequestContext): Promise<codec_0.Label> | codec_0.Label;
}
export interface RendererEvents {
onChanged(callback: (payload: codec_0.Item) => void | Promise<void>): Subscription;
}
export interface AppConnection extends DesktopConnection { readonly host: HostClient; readonly renderer: RendererEvents; setRenderer(handlers: RendererHandlers): Subscription; }
let runtime: Promise<typeof import('./ipc-runtime.js')> | undefined;
export async function connectDesktop(transport: IpcTransport, options?: { renderer?: RendererHandlers; onError?: (error: IpcError) => void }): Promise<AppConnection> {
const implementation = await (runtime ??= import('./ipc-runtime.js'));
return implementation.connectDesktop(transport, options);
}
