// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.3
//   protoc               v7.35.1
// source: types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "example.types";

export interface Metrics {
  infinity: number;
  notANumber: number;
  maximumFixed: bigint;
  minimumFixed: bigint;
  minimumZigzag: bigint;
  maximumFixed32: number;
  minimumFixed32: number;
  maximumUnsigned: number;
  minimumSigned: number;
  truth: boolean;
  details: Metrics_Detail[];
}

export interface Metrics_Detail {
  URLValue: string;
}

function createBaseMetrics(): Metrics {
  return {
    infinity: 0,
    notANumber: 0,
    maximumFixed: 0n,
    minimumFixed: 0n,
    minimumZigzag: 0n,
    maximumFixed32: 0,
    minimumFixed32: 0,
    maximumUnsigned: 0,
    minimumSigned: 0,
    truth: false,
    details: [],
  };
}

export const Metrics: MessageFns<Metrics> = {
  encode(message: Metrics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.infinity !== 0) {
      writer.uint32(9).double(message.infinity);
    }
    if (message.notANumber !== 0) {
      writer.uint32(21).float(message.notANumber);
    }
    if (message.maximumFixed !== 0n) {
      if (BigInt.asUintN(64, message.maximumFixed) !== message.maximumFixed) {
        throw new globalThis.Error("value provided for field message.maximumFixed of type fixed64 too large");
      }
      writer.uint32(25).fixed64(message.maximumFixed);
    }
    if (message.minimumFixed !== 0n) {
      if (BigInt.asIntN(64, message.minimumFixed) !== message.minimumFixed) {
        throw new globalThis.Error("value provided for field message.minimumFixed of type sfixed64 too large");
      }
      writer.uint32(33).sfixed64(message.minimumFixed);
    }
    if (message.minimumZigzag !== 0n) {
      if (BigInt.asIntN(64, message.minimumZigzag) !== message.minimumZigzag) {
        throw new globalThis.Error("value provided for field message.minimumZigzag of type sint64 too large");
      }
      writer.uint32(40).sint64(message.minimumZigzag);
    }
    if (message.maximumFixed32 !== 0) {
      writer.uint32(53).fixed32(message.maximumFixed32);
    }
    if (message.minimumFixed32 !== 0) {
      writer.uint32(61).sfixed32(message.minimumFixed32);
    }
    if (message.maximumUnsigned !== 0) {
      writer.uint32(64).uint32(message.maximumUnsigned);
    }
    if (message.minimumSigned !== 0) {
      writer.uint32(72).int32(message.minimumSigned);
    }
    if (message.truth !== false) {
      writer.uint32(80).bool(message.truth);
    }
    for (const v of message.details) {
      Metrics_Detail.encode(v!, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Metrics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMetrics();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 9) {
              break;
            }

            message.infinity = reader.double();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.notANumber = reader.float();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.maximumFixed = reader.fixed64() as bigint;
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.minimumFixed = reader.sfixed64() as bigint;
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.minimumZigzag = reader.sint64() as bigint;
            continue;
          }
          case 6: {
            if (tag !== 53) {
              break;
            }

            message.maximumFixed32 = reader.fixed32();
            continue;
          }
          case 7: {
            if (tag !== 61) {
              break;
            }

            message.minimumFixed32 = reader.sfixed32();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.maximumUnsigned = reader.uint32();
            continue;
          }
          case 9: {
            if (tag !== 72) {
              break;
            }

            message.minimumSigned = reader.int32();
            continue;
          }
          case 10: {
            if (tag !== 80) {
              break;
            }

            message.truth = reader.bool();
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.details.push(Metrics_Detail.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

function createBaseMetrics_Detail(): Metrics_Detail {
  return { URLValue: "" };
}

export const Metrics_Detail: MessageFns<Metrics_Detail> = {
  encode(message: Metrics_Detail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.URLValue !== "") {
      writer.uint32(10).string(message.URLValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Metrics_Detail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMetrics_Detail();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.URLValue = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
