// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// @generated by webui-desktop-build. Do not edit.
import { BoundaryReader, PayloadWriter, readDelimited, readUint32, readUint64, skipField, IpcError } from '@microsoft/webui-desktop';
export interface Metrics {
infinity: number;
notANumber: number;
maximumFixed: bigint;
minimumFixed: bigint;
minimumZigzag: bigint;
maximumFixed32: number;
minimumFixed32: number;
maximumUnsigned: number;
minimumSigned: number;
truth: boolean;
details: Metrics_Detail[];
}
export interface Metrics_Detail {
URLValue: string;
}
function createBaseMetrics(): Metrics { return {
infinity: 0,
notANumber: 0,
maximumFixed: 0n,
minimumFixed: 0n,
minimumZigzag: 0n,
maximumFixed32: 0,
minimumFixed32: 0,
maximumUnsigned: 0,
minimumSigned: 0,
truth: false,
details: [],
}; }
export const Metrics = {
encode(message: Metrics): Uint8Array { const writer = new PayloadWriter();
if (message.infinity !== 0) { writer.double(1, message.infinity); }
if (message.notANumber !== 0) { writer.float(2, message.notANumber); }
if (message.maximumFixed !== 0n) { writer.fixed64(3, message.maximumFixed); }
if (message.minimumFixed !== 0n) { writer.sfixed64(4, message.minimumFixed); }
if (message.minimumZigzag !== 0n) { writer.sint64(5, message.minimumZigzag); }
if (message.maximumFixed32 !== 0) { writer.fixed32(6, message.maximumFixed32); }
if (message.minimumFixed32 !== 0) { writer.sfixed32(7, message.minimumFixed32); }
if (message.maximumUnsigned !== 0) { writer.uint32(8, message.maximumUnsigned); }
if (message.minimumSigned !== 0) { writer.int32(9, message.minimumSigned); }
if (message.truth) { writer.bool(10, message.truth); }
for (const value of message.details) { writer.bytesField(11, Metrics_Detail.encode(value)); }
return writer.finish(); },
decode(bytes: Uint8Array): Metrics { const reader = new BoundaryReader(bytes); const message = createBaseMetrics(); while (reader.pos < reader.len) { const [number, type] = reader.tag(); switch (number) {
case 1: { message.infinity = reader.double(); break; }
case 2: { message.notANumber = reader.float(); break; }
case 3: { message.maximumFixed = reader.fixed64(); break; }
case 4: { message.minimumFixed = reader.sfixed64(); break; }
case 5: { message.minimumZigzag = (() => { const raw = readUint64(reader); return BigInt.asIntN(64, (raw >> 1n) ^ -(raw & 1n)); })(); break; }
case 6: { message.maximumFixed32 = reader.fixed32(); break; }
case 7: { message.minimumFixed32 = reader.sfixed32(); break; }
case 8: { message.maximumUnsigned = readUint32(reader); break; }
case 9: { message.minimumSigned = Number(BigInt.asIntN(32, readUint64(reader))); break; }
case 10: { message.truth = readUint32(reader) === 1; break; }
case 11: { message.details.push(Metrics_Detail.decode(readDelimited(reader))); break; }
default: skipField(reader, type); break; } } return message; }
};
function createBaseMetrics_Detail(): Metrics_Detail { return {
URLValue: "",
}; }
export const Metrics_Detail = {
encode(message: Metrics_Detail): Uint8Array { const writer = new PayloadWriter();
if (message.URLValue !== "") { writer.string(1, message.URLValue); }
return writer.finish(); },
decode(bytes: Uint8Array): Metrics_Detail { const reader = new BoundaryReader(bytes); const message = createBaseMetrics_Detail(); while (reader.pos < reader.len) { const [number, type] = reader.tag(); switch (number) {
case 1: { message.URLValue = new TextDecoder('utf-8', { fatal: true }).decode(readDelimited(reader)); break; }
default: skipField(reader, type); break; } } return message; }
};
