// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use anyhow::{Context, Result};
use clap::Args;
use expand_tilde::expand_tilde;
use std::fs;
use std::path::PathBuf;
use webui::component_asset_output::{manifest_path, prune};

use crate::utils::{error::CliError, output};

#[derive(Args)]
#[command(
    after_help = "This command does not stop or synchronize other processes. Keep all bundler/HTTP readers and publishers stopped or coordinated until cleanup finishes."
)]
pub(crate) struct PruneArgs {
    /// Existing component input directory produced by build or serve
    #[arg(long, value_name = "DIR")]
    component_assets_out: PathBuf,

    /// Confirm all bundler/HTTP readers and publishers are stopped or coordinated
    #[arg(long, required = true)]
    quiescent: bool,
}

pub(crate) fn execute(args: &PruneArgs) -> Result<()> {
    run(args).inspect_err(|error| {
        output::error(error);
        if let Some(cli_error) = error
            .chain()
            .find_map(|cause| cause.downcast_ref::<CliError>())
        {
            output::hint(cli_error.hint());
        }
    })
}

fn run(args: &PruneArgs) -> Result<()> {
    if !args.quiescent {
        return Err(CliError::ComponentAssetPruneUnconfirmed.into());
    }
    let directory = expand_tilde(&args.component_assets_out)
        .with_context(|| "Failed to expand component asset output path")?;
    let manifest = manifest_path(&directory);
    fs::metadata(&manifest).with_context(|| {
        format!(
            "Cannot read component asset bookkeeping at {}. Pass --component-assets-out for an existing directory generated by webui build or serve.",
            manifest.display()
        )
    })?;
    prune(&directory).with_context(|| {
        format!(
            "Failed to prune component assets in {}. Check the output directory's bookkeeping and file permissions before retrying.",
            directory.display()
        )
    })?;
    output::success(&format!(
        "Pruned obsolete component asset payloads in {}",
        console::style(directory.display()).bold()
    ));
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;
    use tempfile::TempDir;
    use webui::component_asset_output::publish;
    use webui::{BuildOptions, ComponentAssetFile, CssStrategy, Plugin};

    fn args(directory: &Path) -> PruneArgs {
        PruneArgs {
            component_assets_out: directory.to_path_buf(),
            quiescent: true,
        }
    }

    #[test]
    fn cleanup_preserves_current_graph_file_identity_and_application_files() -> Result<()> {
        let app = TempDir::new()?;
        let output = TempDir::new()?;
        fs::write(app.path().join("index.html"), "<p>Application</p>")?;
        fs::write(app.path().join("shared-badge.html"), "<span>Ready</span>")?;
        let mut current_files = Vec::new();
        for version in ["one", "two", "three"] {
            fs::write(
                app.path().join("lazy-card.html"),
                format!("<p>{version}</p><shared-badge></shared-badge>"),
            )?;
            let built = webui::build(BuildOptions {
                app_dir: app.path().to_path_buf(),
                plugin: Some(Plugin::WebUI),
                css: CssStrategy::Style,
                component_asset_roots: vec!["lazy-card".to_string()],
                ..BuildOptions::default()
            })?;
            publish(output.path(), &built.component_asset_files)?;
            current_files = built.component_asset_files;
        }
        assert_eq!(fs::read_dir(output.path().join("components"))?.count(), 4);
        let application_files = [
            "application.js",
            "protocol.bin",
            "component-assets-meta.json",
            "components/application.webui.js",
        ];
        for name in application_files {
            fs::write(output.path().join(name), "application-owned")?;
        }
        let preserved = current_files
            .iter()
            .map(|file| output.path().join(&file.name))
            .chain(std::iter::once(manifest_path(output.path())))
            .chain(
                application_files
                    .iter()
                    .map(|name| output.path().join(name)),
            )
            .map(|path| Ok((fs::read(&path)?, fs::metadata(&path)?.modified()?, path)))
            .collect::<std::io::Result<Vec<_>>>()?;

        for _ in 0..2 {
            execute(&args(output.path()))?;
            assert_eq!(fs::read_dir(output.path().join("components"))?.count(), 3);
            for (bytes, modified, path) in &preserved {
                assert_eq!(fs::read(path)?, *bytes);
                assert_eq!(fs::metadata(path)?.modified()?, *modified);
            }
        }
        Ok(())
    }

    #[test]
    fn cleanup_refuses_unconfirmed_or_invalid_bookkeeping_without_deleting() -> Result<()> {
        let output = TempDir::new()?;
        let payload = ComponentAssetFile {
            name: "components/lazy-card.aaaaaaaaaaaaaaaa.webui.js".to_string(),
            content: "retained payload".to_string(),
        };
        publish(output.path(), std::slice::from_ref(&payload))?;
        let mut unconfirmed = args(output.path());
        unconfirmed.quiescent = false;
        let error = run(&unconfirmed).unwrap_err();
        assert!(matches!(
            error.downcast_ref::<CliError>(),
            Some(CliError::ComponentAssetPruneUnconfirmed)
        ));
        assert_eq!(crate::utils::error::exit_code(&error), 2);

        let manifest = manifest_path(output.path());
        for invalid in ["not json", "{}", r#"{"files":[]}"#] {
            fs::write(&manifest, invalid)?;
            let error = run(&args(output.path())).unwrap_err();
            assert!(error.chain().any(|cause| cause.is::<serde_json::Error>()));
            assert_eq!(crate::utils::error::exit_code(&error), 74);
            assert_eq!(
                fs::read_to_string(output.path().join(&payload.name))?,
                payload.content
            );
        }
        fs::remove_file(&manifest)?;
        let error = run(&args(output.path())).unwrap_err();
        assert_eq!(crate::utils::error::exit_code(&error), 74);
        assert_eq!(
            fs::read_to_string(output.path().join(&payload.name))?,
            payload.content
        );
        Ok(())
    }

    #[test]
    fn cleanup_rejects_missing_and_non_directory_outputs() -> Result<()> {
        let output = TempDir::new()?;
        let missing = output.path().join("missing");
        let error = run(&args(&missing)).unwrap_err();
        assert_eq!(crate::utils::error::exit_code(&error), 74);
        assert!(!missing.exists());

        let file = output.path().join("application.js");
        fs::write(&file, "application-owned")?;
        let error = run(&args(&file)).unwrap_err();
        assert_eq!(crate::utils::error::exit_code(&error), 74);
        assert_eq!(fs::read_to_string(file)?, "application-owned");
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn cleanup_rejects_symlinked_payload_directories() -> Result<()> {
        let output = TempDir::new()?;
        let external = TempDir::new()?;
        publish(
            output.path(),
            &[ComponentAssetFile {
                name: "lazy-card.webui.js".to_string(),
                content: "current root".to_string(),
            }],
        )?;
        let payload = external.path().join("lazy-card.aaaaaaaaaaaaaaaa.webui.js");
        fs::write(&payload, "external payload")?;
        std::os::unix::fs::symlink(external.path(), output.path().join("components"))?;
        let error = run(&args(output.path())).unwrap_err();
        assert_eq!(crate::utils::error::exit_code(&error), 65);
        assert_eq!(fs::read_to_string(payload)?, "external payload");
        Ok(())
    }
}
