[package]
name = "streaming-example-server"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "streaming-example-server"
path = "src/main.rs"

[dependencies]
serde_json = { workspace = true }
microsoft-webui = { path = "../../../../crates/webui" }
microsoft-webui-handler = { path = "../../../../crates/webui-handler" }
microsoft-webui-tokens = { path = "../../../../crates/webui-tokens" }
actix-web = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
futures-util = { workspace = true }
clap = { workspace = true }
mime_guess = { workspace = true }

[lints]
workspace = true
