name: Deploy GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - 'crates/webui-wasm/**'
      - 'crates/webui-parser/**'
      - 'crates/webui-handler/**'
      - 'crates/webui-protocol/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build WASM playground
        uses: ./.github/actions/setup-wasm

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install Dependencies
        run: cd docs && pnpm install

      - name: Build Site
        run: cd docs && pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
