// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::Args;

use crate::{print_field, print_finish, print_header};

/// Arguments for `webui desktop init`.
#[derive(Args)]
pub(crate) struct InitArgs {
    /// Directory in which to create the desktop app.
    #[arg(default_value = ".")]
    pub(crate) path: PathBuf,

    /// Replace files generated by a previous init.
    #[arg(long)]
    pub(crate) force: bool,
}

pub(crate) fn execute(args: &InitArgs) -> Result<()> {
    let root = args
        .path
        .canonicalize()
        .unwrap_or_else(|_| args.path.clone());
    fs::create_dir_all(&root)
        .with_context(|| format!("failed to create app directory {}", root.display()))?;

    let files = generated_files(&root);
    let conflicts: Vec<&Path> = files
        .iter()
        .map(|(path, _)| path.as_path())
        .filter(|path| path.exists())
        .collect();
    if !conflicts.is_empty() && !args.force {
        let names = conflicts
            .iter()
            .map(|path| {
                path.strip_prefix(&root)
                    .unwrap_or(path)
                    .display()
                    .to_string()
            })
            .collect::<Vec<_>>()
            .join(", ");
        return Err(anyhow::anyhow!(
            "desktop init would overwrite existing files: {names}; help: choose an empty directory or rerun with --force"
        ));
    }

    print_header("WebUI Desktop Init");
    for (path, content) in files {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create {}", parent.display()))?;
        }
        fs::write(&path, content).with_context(|| format!("failed to write {}", path.display()))?;
        print_field(
            "Created",
            &path.strip_prefix(&root).unwrap_or(&path).display(),
        );
    }
    print_finish("Desktop app scaffold complete");
    Ok(())
}

fn generated_files(root: &Path) -> Vec<(PathBuf, String)> {
    vec![
        (root.join("package.json"), PACKAGE_JSON.to_string()),
        (root.join("src/index.html"), INDEX_HTML.to_string()),
        (root.join("desktop/Cargo.toml"), desktop_cargo_toml()),
        (root.join("desktop/src/main.rs"), DESKTOP_MAIN.to_string()),
    ]
}

const PACKAGE_JSON: &str = r#"{
  "name": "webui-desktop-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "webui build ./src --out ./dist"
  },
  "webuiDesktop": {
    "app": "src",
    "assets": "dist",
    "runnerCrate": "webui-desktop-app",
    "appId": "com.example.webui.desktop",
    "appName": "WebUI Desktop App",
    "title": "WebUI Desktop App",
    "width": 1200,
    "height": 800
  }
}
"#;

const INDEX_HTML: &str = r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WebUI Desktop App</title>
</head>
<body>
  <main>
    <h1>WebUI Desktop App</h1>
    <p>Edit <code>src/index.html</code> to get started.</p>
  </main>
</body>
</html>
"#;

fn desktop_cargo_toml() -> String {
    let workspace = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let dependencies = [
        ("webui", "microsoft-webui"),
        ("webui-desktop", "microsoft-webui-desktop"),
        ("webui-desktop-runner", "microsoft-webui-desktop-runner"),
    ];
    let mut text = String::from(
        r#"[package]
name = "webui-desktop-app"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "webui-desktop-app"
path = "src/main.rs"

[dependencies]
anyhow = "1"
"#,
    );
    for (name, package) in dependencies {
        let crate_dir = workspace
            .join("crates")
            .join(package.strip_prefix("microsoft-").unwrap_or(package));
        if crate_dir.is_dir() {
            text.push_str(&format!(
                "{name} = {{ package = \"{package}\", path = \"{}\"{} }}\n",
                crate_dir.display(),
                if name == "webui" {
                    ", features = [\"cli\"]"
                } else {
                    ""
                }
            ));
        } else if name == "webui" {
            text.push_str(&format!("{name} = {{ package = \"{package}\", version = \"0.0.29\", features = [\"cli\"] }}\n"));
        } else {
            text.push_str(&format!(
                "{name} = {{ package = \"{package}\", version = \"0.0.29\" }}\n"
            ));
        }
    }
    text
}

const DESKTOP_MAIN: &str = r#"// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use std::path::Path;
use std::sync::Arc;

use anyhow::Result;
use webui::{BuildOptions, DEFAULT_CSS_FILE_NAME_TEMPLATE};
use webui_desktop::{DesktopBundleConfig, DesktopBundleManifest, DesktopRuntime, DesktopSourceConfig, WindowOptions};

fn main() -> Result<()> {
    let (runtime, window) = match webui_desktop_runner::find_packaged_resources_dir() {
        Some(resources) => packaged_runtime(&resources)?,
        None => source_runtime()?,
    };
    webui_desktop_runner::run_runtime(Arc::new(runtime), window)
}

fn source_runtime() -> Result<(DesktopRuntime, WindowOptions)> {
    let app_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("src");
    let options = BuildOptions {
        app_dir,
        entry: "index.html".to_string(),
        css_file_name_template: DEFAULT_CSS_FILE_NAME_TEMPLATE.to_string(),
        ..Default::default()
    };
    let runtime = DesktopRuntime::from_source(DesktopSourceConfig::new(options))?;
    Ok((runtime, WindowOptions::default()))
}

fn packaged_runtime(resources: &Path) -> Result<(DesktopRuntime, WindowOptions)> {
    let manifest = DesktopBundleManifest::load(&resources.join("manifest.webui-desktop.json"))?;
    let window = manifest.window.clone();
    let runtime = DesktopRuntime::from_bundle_config_and_manifest(
        DesktopBundleConfig::new(resources.to_path_buf()),
        manifest,
    )?;
    Ok((runtime, window))
}
"#;

#[cfg(test)]
#[allow(clippy::disallowed_methods)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn creates_scaffold_and_runner() {
        let temp = TempDir::new().unwrap();
        execute(&InitArgs {
            path: temp.path().join("app"),
            force: false,
        })
        .unwrap();
        assert!(temp.path().join("app/package.json").is_file());
        assert!(temp.path().join("app/src/index.html").is_file());
        assert!(temp.path().join("app/desktop/src/main.rs").is_file());
        assert!(
            fs::read_to_string(temp.path().join("app/desktop/src/main.rs"))
                .unwrap()
                .contains("..Default::default()")
        );
    }

    #[test]
    fn refuses_existing_generated_files_without_force() {
        let temp = TempDir::new().unwrap();
        fs::create_dir_all(temp.path().join("app")).unwrap();
        fs::write(temp.path().join("app/package.json"), "{}").unwrap();
        let error = execute(&InitArgs {
            path: temp.path().join("app"),
            force: false,
        })
        .unwrap_err()
        .to_string();
        assert!(error.contains("--force"));
    }
}
